#!/usr/bin/env python

"""
download remote assets

remote assets are defined by `remote_assets/*.url` files within the package and
end up in the adjacent `assets` directory, using the corresponding filename
"""

import sys
import os

from urllib import urlretrieve

from tiddlyweb.util import std_error_message


def main(args):
    pkg_path = os.path.join('tiddlywebplugins', 'bfw')
    source_path = os.path.join(pkg_path, 'remote_assets')
    target_path = os.path.join(pkg_path, 'assets')

    for filename in os.listdir(source_path):
        source = os.path.join(source_path, filename)
        target = os.path.join(target_path, filename[:-4]) # strip ".url"
        with open(source) as fh:
            url = fh.read().strip()
            std_error_message('downloading %s from %s' % (target, url))
            urlretrieve(url, target)

    return True


if __name__ == '__main__':
    status = not main(sys.argv)
    sys.exit(status)
